name: barista
description: Couvee barista app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  path_provider: ^1.6.11
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  http: ^0.12.2
  google_fonts: ^1.1.0
  wc_form_validators: ^0.1.1
  intl: ^0.16.1
  passcode_screen: ^1.2.0
  eva_icons_flutter: ^2.0.0
  qr_code_scanner: ^0.0.13
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.0
  flutter_launcher_icons: "^0.7.5"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
